// Auto-generated by Vasp — entity interfaces derived from .vasp schema
// Re-run `vasp build` or restart `vasp start` to regenerate

export interface User {
  id: number
  username: string
  email: string
  role: 'admin' | 'editor' | 'viewer'
  displayName: string | null
  bio: string | null
  avatar: string | null
  isActive: boolean
  pages: Page[]
  comments: Comment[]
  spaces: Space[]
  createdAt: Date
  updatedAt: Date
}

export interface CreateUserInput {
  username: string
  email: string
  role: 'admin' | 'editor' | 'viewer'
  displayName?: string | null
  bio?: string | null
  avatar?: string | null
  isActive: boolean
}

export interface UpdateUserInput {
  username?: string
  email?: string
  role?: 'admin' | 'editor' | 'viewer'
  displayName?: string | null
  bio?: string | null
  avatar?: string | null
  isActive?: boolean
}

export interface Space {
  id: number
  name: string
  key: string
  description: string | null
  iconUrl: string | null
  isPublic: boolean
  owner: User
  ownerId: number
  pages: Page[]
  createdAt: Date
  updatedAt: Date
}

export interface CreateSpaceInput {
  name: string
  key: string
  description?: string | null
  iconUrl?: string | null
  isPublic: boolean
  ownerId: number
}

export interface UpdateSpaceInput {
  name?: string
  key?: string
  description?: string | null
  iconUrl?: string | null
  isPublic?: boolean
  ownerId?: number
}

export interface Page {
  id: number
  title: string
  body: RichText | null
  status: 'draft' | 'published' | 'archived'
  version: number
  excerpt: string | null
  slug: string | null
  isFeatured: boolean
  viewCount: number
  space: Space
  spaceId: number
  author: User
  authorId: number
  parent: Page | null
  parentId: number | null
  children: Page[]
  comments: Comment[]
  attachments: Attachment[]
  labels: Label[]
  versions: PageVersion[]
  createdAt: Date
  updatedAt: Date
}

export interface CreatePageInput {
  title: string
  body?: RichText | null
  status: 'draft' | 'published' | 'archived'
  version: number
  excerpt?: string | null
  slug?: string | null
  isFeatured: boolean
  viewCount: number
  spaceId: number
  authorId: number
  parentId?: number
}

export interface UpdatePageInput {
  title?: string
  body?: RichText | null
  status?: 'draft' | 'published' | 'archived'
  version?: number
  excerpt?: string | null
  slug?: string | null
  isFeatured?: boolean
  viewCount?: number
  spaceId?: number
  authorId?: number
  parentId?: number | null
}

export interface PageVersion {
  id: number
  version: number
  title: string
  body: RichText | null
  changeNote: string | null
  page: Page
  pageId: number
  author: User
  authorId: number
  createdAt: Date
  updatedAt: Date
}

export interface CreatePageVersionInput {
  version: number
  title: string
  body?: RichText | null
  changeNote?: string | null
  pageId: number
  authorId: number
}

export interface UpdatePageVersionInput {
  version?: number
  title?: string
  body?: RichText | null
  changeNote?: string | null
  pageId?: number
  authorId?: number
}

export interface Comment {
  id: number
  content: string
  isEdited: boolean
  editedAt: Date | null
  page: Page
  pageId: number
  author: User
  authorId: number
  parent: Comment | null
  parentId: number | null
  replies: Comment[]
  createdAt: Date
  updatedAt: Date
}

export interface CreateCommentInput {
  content: string
  isEdited: boolean
  editedAt?: Date | null
  pageId: number
  authorId: number
  parentId?: number
}

export interface UpdateCommentInput {
  content?: string
  isEdited?: boolean
  editedAt?: Date | null
  pageId?: number
  authorId?: number
  parentId?: number | null
}

export interface Label {
  id: number
  name: string
  color: string | null
  pages: Page[]
  createdAt: Date
  updatedAt: Date
}

export interface CreateLabelInput {
  name: string
  color?: string | null
}

export interface UpdateLabelInput {
  name?: string
  color?: string | null
}

export interface Attachment {
  id: number
  filename: string
  mimeType: string
  sizeBytes: number
  url: string
  page: Page
  pageId: number
  uploadedBy: User
  uploadedById: number
  createdAt: Date
  updatedAt: Date
}

export interface CreateAttachmentInput {
  filename: string
  mimeType: string
  sizeBytes: number
  url: string
  pageId: number
  uploadedById: number
}

export interface UpdateAttachmentInput {
  filename?: string
  mimeType?: string
  sizeBytes?: number
  url?: string
  pageId?: number
  uploadedById?: number
}

export interface PageWatch {
  id: number
  user: User
  userId: number
  page: Page
  pageId: number
  createdAt: Date
  updatedAt: Date
}

export interface CreatePageWatchInput {
  userId: number
  pageId: number
}

export interface UpdatePageWatchInput {
  userId?: number
  pageId?: number
}

export type GetSpacesArgs = Record<string, unknown>
export type GetSpacesReturn = unknown
export type GetSpaceArgs = Record<string, unknown>
export type GetSpaceReturn = unknown
export type GetPageTreeArgs = Record<string, unknown>
export type GetPageTreeReturn = unknown
export type GetPageArgs = Record<string, unknown>
export type GetPageReturn = unknown
export type GetPageVersionsArgs = Record<string, unknown>
export type GetPageVersionsReturn = unknown
export type SearchPagesArgs = Record<string, unknown>
export type SearchPagesReturn = unknown
export type GetRecentlyUpdatedPagesArgs = Record<string, unknown>
export type GetRecentlyUpdatedPagesReturn = unknown
export type GetPageCommentsArgs = Record<string, unknown>
export type GetPageCommentsReturn = unknown
export type CreateSpaceArgs = Record<string, unknown>
export type CreateSpaceReturn = unknown
export type UpdateSpaceArgs = Record<string, unknown>
export type UpdateSpaceReturn = unknown
export type CreatePageArgs = Record<string, unknown>
export type CreatePageReturn = unknown
export type UpdatePageArgs = Record<string, unknown>
export type UpdatePageReturn = unknown
export type PublishPageArgs = Record<string, unknown>
export type PublishPageReturn = unknown
export type MovePageArgs = Record<string, unknown>
export type MovePageReturn = unknown
export type RestorePageVersionArgs = Record<string, unknown>
export type RestorePageVersionReturn = unknown
export type DeletePageArgs = Record<string, unknown>
export type DeletePageReturn = unknown
export type CreateCommentArgs = Record<string, unknown>
export type CreateCommentReturn = unknown
export type DeleteCommentArgs = Record<string, unknown>
export type DeleteCommentReturn = unknown
export type AddLabelArgs = Record<string, unknown>
export type AddLabelReturn = unknown
export type RemoveLabelArgs = Record<string, unknown>
export type RemoveLabelReturn = unknown
export type WatchPageArgs = Record<string, unknown>
export type WatchPageReturn = unknown
export type UnwatchPageArgs = Record<string, unknown>
export type UnwatchPageReturn = unknown
