import { join, resolve } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { log } from "../utils/logger.js";

type DeployTarget = "docker" | "fly" | "railway";

interface DeployOptions {
  target: DeployTarget;
  force: boolean;
}

function parseArgs(args: string[]): DeployOptions {
  let target: DeployTarget | undefined;
  let force = false;

  for (const arg of args) {
    if (arg === "--force" || arg === "-f") {
      force = true;
    } else if (arg.startsWith("--target=")) {
      target = arg.slice("--target=".length) as DeployTarget;
    } else if (arg === "--target" || arg === "-t") {
      // handled by next arg — not supported in this simple parser; require --target=value
    }
  }

  if (!target) {
    log.error(
      "Missing --target. Usage: vasp deploy --target=<docker|fly|railway>",
    );
    log.info("");
    log.info("Available targets:");
    log.info("  --target=docker    Generate Dockerfile + docker-compose.yml");
    log.info("  --target=fly       Generate fly.toml + Dockerfile for Fly.io");
    log.info(
      "  --target=railway   Generate railway.json + Dockerfile for Railway",
    );
    process.exit(1);
  }

  const validTargets: DeployTarget[] = ["docker", "fly", "railway"];
  if (!validTargets.includes(target)) {
    log.error(`Unknown target: ${target}. Valid targets: docker, fly, railway`);
    process.exit(1);
  }

  return { target, force };
}

interface ProjectInfo {
  appName: string;
  isSsr: boolean;
  backendPort: number;
  frontendPort: number;
}

function readProjectInfo(projectDir: string): ProjectInfo {
  const pkgFile = join(projectDir, "package.json");
  if (!existsSync(pkgFile)) {
    log.error("No package.json found. Run this command inside a Vasp project.");
    process.exit(1);
  }

  const pkg = JSON.parse(readFileSync(pkgFile, "utf8")) as {
    name?: string;
    dependencies?: Record<string, string>;
  };

  return {
    appName: pkg.name ?? "vasp-app",
    isSsr: !!pkg.dependencies?.["nuxt"],
    backendPort: 3001,
    frontendPort: 3000,
  };
}

function writeFile(filePath: string, content: string, force: boolean): boolean {
  if (existsSync(filePath) && !force) {
    log.warn(
      `  ${filePath} already exists — skipping (use --force to overwrite)`,
    );
    return false;
  }
  writeFileSync(filePath, content, "utf8");
  log.success(`  Created ${filePath}`);
  return true;
}

function generateDockerfile(info: ProjectInfo): string {
  const frontendCopy = info.isSsr
    ? "COPY --from=builder /app/.output ./.output"
    : "COPY --from=builder /app/dist ./dist";

  const startCmd = info.isSsr
    ? `CMD ["bun", "dist/server/index.js"]`
    : `CMD ["bun", "dist/server/index.js"]`;

  return `# Multi-stage Dockerfile generated by Vasp
# Stage 1: Builder — install deps and build the app
FROM oven/bun:1 AS builder
WORKDIR /app

COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

# Stage 2: Runner — lean production image
FROM oven/bun:1-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/server ./dist/server
${frontendCopy}

EXPOSE ${info.backendPort}

${startCmd}
`;
}

function generateDockerCompose(info: ProjectInfo): string {
  const services = info.isSsr
    ? `  app:
    build: .
    ports:
      - "${info.backendPort}:${info.backendPort}"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/${info.appName}
      - NODE_ENV=production
      - PORT=${info.backendPort}
    depends_on:
      db:
        condition: service_healthy

  nuxt:
    image: node:20-alpine
    working_dir: /app
    command: node .output/server/index.mjs
    volumes:
      - ./.output:/app/.output
    ports:
      - "${info.frontendPort}:3000"
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_BASE=http://app:${info.backendPort}/api
    depends_on:
      - app`
    : `  app:
    build: .
    ports:
      - "${info.backendPort}:${info.backendPort}"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/${info.appName}
      - NODE_ENV=production
      - PORT=${info.backendPort}
    depends_on:
      db:
        condition: service_healthy`;

  return `# docker-compose.yml generated by Vasp
# Usage: docker-compose up --build
services:
${services}

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${info.appName}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
`;
}

function generateDockerIgnore(): string {
  return `node_modules
.env
.git
.vasp
.vasp-staging-*
dist
.output
*.log
*.md
tests
`;
}

function generateFlyToml(info: ProjectInfo): string {
  return `# fly.toml generated by Vasp
# Docs: https://fly.io/docs/reference/configuration/
app = "${info.appName}"
primary_region = "iad"

[build]

[http_service]
  internal_port = ${info.backendPort}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "${info.backendPort}"
  NODE_ENV = "production"
`;
}

function generateRailwayJson(info: ProjectInfo): string {
  return (
    JSON.stringify(
      {
        $schema: "https://railway.app/railway.schema.json",
        build: {
          builder: "DOCKERFILE",
          dockerfilePath: "./Dockerfile",
        },
        deploy: {
          startCommand: `bun dist/server/index.js`,
          healthcheckPath: "/api/health",
          healthcheckTimeout: 300,
          restartPolicyType: "ON_FAILURE",
          restartPolicyMaxRetries: 10,
        },
      },
      null,
      2,
    ) + "\n"
  );
}

export async function deployCommand(args: string[] = []): Promise<void> {
  const options = parseArgs(args);
  const projectDir = resolve(process.cwd());
  const info = readProjectInfo(projectDir);

  log.step(`Generating deployment files for target: ${options.target}`);
  log.dim(
    `  App: ${info.appName} | Mode: ${info.isSsr ? "SSR (Nuxt)" : "SPA (Vite)"}`,
  );
  console.log();

  switch (options.target) {
    case "docker": {
      writeFile(
        join(projectDir, "Dockerfile"),
        generateDockerfile(info),
        options.force,
      );
      writeFile(
        join(projectDir, "docker-compose.yml"),
        generateDockerCompose(info),
        options.force,
      );
      writeFile(
        join(projectDir, ".dockerignore"),
        generateDockerIgnore(),
        options.force,
      );

      console.log();
      log.info("Next steps:");
      log.dim(
        "  1. Edit DATABASE_URL in docker-compose.yml (or use a secrets manager)",
      );
      log.dim("  2. docker-compose up --build");
      log.dim(
        `  3. Visit http://localhost:${info.backendPort}/api/health to verify`,
      );
      break;
    }

    case "fly": {
      writeFile(
        join(projectDir, "Dockerfile"),
        generateDockerfile(info),
        options.force,
      );
      writeFile(
        join(projectDir, ".dockerignore"),
        generateDockerIgnore(),
        options.force,
      );
      writeFile(
        join(projectDir, "fly.toml"),
        generateFlyToml(info),
        options.force,
      );

      console.log();
      log.info("Next steps:");
      log.dim("  1. fly launch --no-deploy  (if not already initialized)");
      log.dim("  2. fly secrets set DATABASE_URL=<your-postgres-url>");
      log.dim("  3. fly deploy");
      log.dim("  Docs: https://fly.io/docs/languages-and-frameworks/node/");
      break;
    }

    case "railway": {
      writeFile(
        join(projectDir, "Dockerfile"),
        generateDockerfile(info),
        options.force,
      );
      writeFile(
        join(projectDir, ".dockerignore"),
        generateDockerIgnore(),
        options.force,
      );
      writeFile(
        join(projectDir, "railway.json"),
        generateRailwayJson(info),
        options.force,
      );

      console.log();
      log.info("Next steps:");
      log.dim("  1. Push your code to GitHub");
      log.dim("  2. railway init && railway up");
      log.dim("  3. Set DATABASE_URL in Railway dashboard → Variables");
      log.dim("  Docs: https://docs.railway.app/deploy/dockerfiles");
      break;
    }
  }

  console.log();
  log.info("Run `vasp build` first to produce the production build artifacts.");
}
