// Auto-generated by Vasp — do not edit directly
// https://nuxt.com/docs/api/configuration/nuxt-config
import Aura from '@primevue/themes/aura'
import { definePreset } from '@primevue/themes'

const AppTheme = definePreset(Aura, {
  semantic: {
    primary: {
      50: '{blue.50}',
      100: '{blue.100}',
      200: '{blue.200}',
      300: '{blue.300}',
      400: '{blue.400}',
      500: '{blue.500}',
      600: '{blue.600}',
      700: '{blue.700}',
      800: '{blue.800}',
      900: '{blue.900}',
      950: '{blue.950}',
    },
  },
})

export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  devServer: {
    port: 3000,
  },
  typescript: {
    strict: false,
    typeCheck: false,
    tsConfig: {
      compilerOptions: {
        baseUrl: '.',
      },
    },
  },
  modules: ['@primevue/nuxt-module'],
  primevue: {
    options: {
      ripple: true,
      theme: {
        preset: AppTheme,
        options: { darkModeSelector: '.app-dark' },
      },
    },
  },
  css: ['primeicons/primeicons.css'],
  alias: {
    '@src': '~/src',
    '@shared': '~/shared',
  },
  nitro: {
    ignore: ['**'],
    scanDirs: [],
  },
  // Proxy /api/* → Elysia backend in development (avoids CORS + cross-origin cookie issues)
  // Nitro expands the '**' wildcard in both the pattern and target, so '/api/**' with
  // target 'http://host/api/**' correctly maps /api/foo → http://host/api/foo.
  routeRules: {
    '/api/**': { proxy: 'http://localhost:3001/api/**' },
  },
  runtimeConfig: {
    backendUrl: process.env.BACKEND_URL || 'http://localhost:3001',
    public: {
      apiBase: process.env.API_BASE || 'http://localhost:3001/api',
    },
  },
})
