import { join } from "node:path";
import { ensureDir } from "../utils/fs.js";
import { BaseGenerator } from "./BaseGenerator.js";
import { DEFAULT_BACKEND_PORT } from "@vasp-framework/core";
import { toCamelCase } from "../template/TemplateEngine.js";

export class AdminGenerator extends BaseGenerator {
  run(): void {
    const { ast, ext } = this.ctx;
    if (!ast.admin) return;

    this.ctx.logger.info("Generating admin panel...");

    const entityMap = new Map(ast.entities.map((e) => [e.name, e]));

    // Resolve admin entities to their full EntityNode definitions
    const adminEntities = ast.admin.entities.map((name) => {
      const entity = entityMap.get(name);
      return (
        entity ?? {
          name,
          fields: [],
          type: "Entity" as const,
          loc: ast.admin!.loc,
        }
      );
    });

    // Create directory structure inside the main SPA/SSR src/ directory.
    // The admin panel is integrated as a lazy-loaded /admin route group so it
    // shares the same node_modules, Vite process, and deployment origin.
    const adminDirs = [
      "src/admin/views/dashboard",
      "src/admin/api",
      ...adminEntities.map(
        (e) => `src/admin/views/${this.toKebabCase(e.name)}`,
      ),
    ];
    for (const dir of adminDirs) {
      ensureDir(join(this.ctx.outputDir, dir));
    }

    // Create backend admin route directories
    ensureDir(join(this.ctx.outputDir, "server/routes/admin"));

    const commonData = {
      adminEntities,
      backendPort: DEFAULT_BACKEND_PORT,
    };

    // ── Frontend files (integrated into main SPA/SSR) ─────────────────

    // Admin layout component — used as the /admin parent route (SPA) or Nuxt layout (SSR)
    this.write(
      "src/admin/AdminLayout.vue",
      this.render("admin/src/layouts/AdminLayout.vue.hbs", commonData),
    );

    // Dashboard view
    this.write(
      "src/admin/views/Dashboard.vue",
      this.render("admin/src/views/dashboard/index.vue.hbs", commonData),
    );

    // Per-entity: API client + list view + form modal
    for (const entity of adminEntities) {
      // Pre-compute many-to-one relation metadata so templates can render FK selects.
      // Only singular (non-array) relation fields have a physical FK column on this table;
      // one-to-many (array) relations are virtual and stored on the related entity's side.
      const manyToOneRelations = entity.fields
        .filter((f) => f.isRelation && !f.isArray)
        .map((f) => ({
          name: f.name,
          fkName: `${f.name}Id`,
          relatedEntity: f.relatedEntity,
          nullable: f.nullable,
        }));
      // Deduplicated list of related entity names (for generating unique API imports)
      const uniqueRelatedEntities = [
        ...new Set(
          manyToOneRelations.map((r) => r.relatedEntity).filter(Boolean),
        ),
      ];

      // Annotate scalar fields that would duplicate an FK already generated by a relation field.
      // e.g. when entity has both `categoryId: Int` and `category: Category`, only the
      // relation-generated FK should appear in the form's emptyForm() to avoid duplicate keys.
      const relationFkNames = new Set(manyToOneRelations.map((r) => r.fkName));
      const annotatedFields = entity.fields.map((f) => ({
        ...f,
        isExplicitFkDuplicate: !f.isRelation && relationFkNames.has(f.name),
      }));

      const entityData = {
        ...commonData,
        ...entity,
        fields: annotatedFields,
        manyToOneRelations,
        hasManyToOneRelations: manyToOneRelations.length > 0,
        uniqueRelatedEntities,
      };
      const kebabName = this.toKebabCase(entity.name);

      this.write(
        `src/admin/api/${kebabName}.${ext}`,
        this.render("admin/src/api/_entity.hbs", entityData),
      );

      this.write(
        `src/admin/views/${kebabName}/index.vue`,
        this.render("admin/src/views/_entity/index.vue.hbs", entityData),
      );

      this.write(
        `src/admin/views/${kebabName}/FormModal.vue`,
        this.render("admin/src/views/_entity/FormModal.vue.hbs", entityData),
      );
    }

    // ── SSR (Nuxt): generate admin layout + per-page wrappers ─────────
    // For SSR the admin components above are imported into Nuxt pages so that
    // Nuxt handles routing via the file-system, and the layout uses <slot />.
    if (this.ctx.isSsr) {
      ensureDir(join(this.ctx.outputDir, "layouts"));
      ensureDir(join(this.ctx.outputDir, "pages/admin"));
      for (const entity of adminEntities) {
        ensureDir(
          join(
            this.ctx.outputDir,
            `pages/admin/${this.toKebabCase(entity.name)}`,
          ),
        );
      }

      this.write(
        "layouts/admin.vue",
        this.render("admin/layouts/admin.vue.hbs", commonData),
      );

      this.write(
        "pages/admin/index.vue",
        this.render("admin/pages/dashboard.vue.hbs", commonData),
      );

      for (const entity of adminEntities) {
        const kebabName = this.toKebabCase(entity.name);
        this.write(
          `pages/admin/${kebabName}/index.vue`,
          this.render("admin/pages/_entity.vue.hbs", {
            ...commonData,
            entity: entity.name,
          }),
        );
      }
    }

    // ── Backend admin routes ──────────────────────────────────────────

    // Per-entity server-side admin CRUD handler
    for (const entity of adminEntities) {
      this.write(
        `server/routes/admin/${toCamelCase(entity.name)}.${ext}`,
        this.render("shared/server/routes/admin/_admin.hbs", {
          ...commonData,
          entity: entity.name,
        }),
      );
    }

    // Admin routes aggregator (imported by server/index.{ext})
    this.write(
      `server/routes/admin/index.${ext}`,
      this.render("shared/server/routes/admin/index.hbs", commonData),
    );
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/([A-Z])/g, "-$1")
      .replace(/[\s_]+/g, "-")
      .toLowerCase()
      .replace(/^-/, "");
  }
}
