import { DEFAULT_BACKEND_PORT } from "@vasp-framework/core";
import { BaseGenerator } from "./BaseGenerator.js";
import { toCamelCase, toPlural } from "../template/TemplateEngine.js";

export class AuthGenerator extends BaseGenerator {
  run(): void {
    if (!this.ctx.ast.auth) return;

    this.ctx.logger.info("Generating auth system...");

    const { ext, ast } = this.ctx;
    const authMethods = ast.auth!.methods;
    const authPermissions = ast.auth!.permissions ?? {};
    const hasPermissions = Object.keys(authPermissions).length > 0;

    // Transform the permissions map into a template-friendly array of entries
    const permissionEntries = Object.entries(authPermissions).map(
      ([name, roles]) => ({ name, roles }),
    );

    // Collect many-to-one relation fields on the user entity.
    // These generate {name}Id FK columns in the DB that the register endpoint
    // may need to accept (e.g. workspaceId when User belongs to a Workspace).
    const userEntity = ast.entities.find(
      (e) => e.name === ast.auth!.userEntity,
    );
    const userFkFields = (userEntity?.fields ?? [])
      .filter((f) => f.isRelation && !f.isArray)
      .map((f) => ({ fieldName: `${toCamelCase(f.name)}Id` }));
    const hasUserFkFields = userFkFields.length > 0;

    // Detect password field name (either 'password' or 'passwordHash')
    const passwordField = userEntity?.fields.find(
      (f) => f.name === "password" || f.name === "passwordHash",
    );
    const passwordFieldName = passwordField?.name || "passwordHash";

    // Derive the Drizzle table const name from the user entity name.
    // Matches the convention used in DrizzleSchemaGenerator: toPlural(camelCase(name)).
    // e.g. "User" → "users", "Account" → "accounts", "Person" → "people"
    const userTableName = toPlural(toCamelCase(ast.auth!.userEntity));

    const data = {
      authMethods,
      backendPort: DEFAULT_BACKEND_PORT,
      hasPermissions,
      permissionEntries,
      userFkFields,
      hasUserFkFields,
      passwordFieldName,
      userTableName,
    };

    // Server: auth plugin (JWT + cookie — separate file to avoid circular imports)
    this.write(
      `server/auth/plugin.${ext}`,
      this.render("shared/auth/server/plugin.hbs", data),
    );

    // Server: auth routes + JWT middleware
    this.write(
      `server/auth/index.${ext}`,
      this.render("shared/auth/server/index.hbs", data),
    );
    this.write(
      `server/auth/middleware.${ext}`,
      this.render("shared/auth/server/middleware.hbs", data),
    );

    // Server: providers
    if (authMethods.includes("usernameAndPassword")) {
      this.write(
        `server/auth/providers/usernameAndPassword.${ext}`,
        this.render(
          "shared/auth/server/providers/usernameAndPassword.hbs",
          data,
        ),
      );
    }
    if (authMethods.includes("google")) {
      this.write(
        `server/auth/providers/google.${ext}`,
        this.render("shared/auth/server/providers/google.hbs", data),
      );
    }
    if (authMethods.includes("github")) {
      this.write(
        `server/auth/providers/github.${ext}`,
        this.render("shared/auth/server/providers/github.hbs", data),
      );
    }

    // Client: auth composable (SPA only — SSR uses composables/useAuth generated by FrontendGenerator)
    if (this.ctx.isSpa) {
      this.write(
        `src/vasp/auth.${ext}`,
        this.render(`spa/${ext}/src/vasp/auth.${ext}.hbs`, data),
      );
    }

    // Login/Register Vue components (used by both SPA router and SSR Nuxt page wrappers)
    this.write(
      "src/pages/Login.vue",
      this.render("shared/auth/client/Login.vue.hbs", data),
    );
    this.write(
      "src/pages/Register.vue",
      this.render("shared/auth/client/Register.vue.hbs", data),
    );
  }
}
