// Auto-generated by Vasp — do not edit directly
export default defineNuxtRouteMiddleware(async (to) => {
  const { user, checkAuth } = useAuth()
  const publicPaths = ['/login', '/register']
  // checkAuth() calls /auth/me once per SSR request (no-op if already checked).
  // Without this, user is always null on the server and every protected route
  // redirects to /login even when the browser sends a valid session cookie.
  await checkAuth()
  if (!user.value && !publicPaths.includes(to.path)) {
    return navigateTo('/login')
  }
})
