// Auto-generated by Vasp — do not edit
import { createVaspClient } from '@vasp-framework/runtime'
import { notifyError } from '../useVaspNotifications.js'

// Module-level singleton — safe to call from any context (event handlers, stores, etc.)
const _client = createVaspClient({ baseURL: import.meta.env.VITE_API_URL || '/api' })

/**
 * Call the 'registerUser' action on the Vasp backend.
 * @param {unknown} args - Arguments to pass to the action function
 * @returns {Promise<unknown>}
 */
export async function registerUser(args) {
  try {
    return await _client.action('registerUser', args)
  } catch (error) {
    notifyError(error)
    throw error
  }
}

