// Auto-generated by Vasp — do not edit directly
// https://nuxt.com/docs/api/configuration/nuxt-config
import Aura from '@primevue/themes/aura'
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  devServer: {
    port: 3000,
  },
  typescript: {
    strict: false,
    typeCheck: false,
    tsConfig: {
      compilerOptions: {
        baseUrl: '.',
      },
    },
  },
  modules: ['@primevue/nuxt-module'],
  primevue: {
    options: {
      ripple: true,
      theme: {
        preset: Aura,
        options: { darkModeSelector: '.app-dark' },
      },
    },
  },
  css: ['primeicons/primeicons.css'],
  alias: {
    '@src': '~/src',
    '@shared': '~/shared',
  },
  nitro: {
    ignore: ['**'],
    scanDirs: [],
  },
  runtimeConfig: {
    backendUrl: process.env.BACKEND_URL || 'http://localhost:3001',
    public: {
      apiBase: process.env.API_BASE || 'http://localhost:3001/api',
    },
  },
})
