// Auto-generated by Vasp — do not edit
import { ref, onMounted, onUnmounted } from 'vue'

const WS_BASE = typeof window !== 'undefined'
  ? (window.__NUXT_APP_CONFIG__?.wsUrl ?? `ws://${window.location.host}`)
  : ''

export interface RealtimeMessage {
  channel: string
  event: string
  data: unknown
}

export interface UseRealtimeResult {
  connected: ReturnType<typeof ref<boolean>>
  on: (event: string, handler: (data: unknown) => void) => void
  disconnect: () => void
}

/**
 * useRealtime — subscribe to a Vasp realtime channel.
 * Works client-side only in SSR/Nuxt apps (WebSocket is a browser API).
 *
 * @example
 * const { on } = useRealtime('todoChannel')
 * on('created', (todo) => todos.value.push(todo))
 */
export function useRealtime(channelName: string): UseRealtimeResult {
  const connected = ref(false)
  const handlers = new Map<string, (data: unknown) => void>()
  let ws: WebSocket | null = null
  let reconnectTimer: ReturnType<typeof setTimeout> | null = null
  let intentionallyClosed = false

  function connect() {
    if (typeof window === 'undefined') return // SSR guard
    ws = new WebSocket(`${WS_BASE}/ws/${channelName}`)

    ws.onopen = () => { connected.value = true }
    ws.onclose = () => {
      connected.value = false
      if (!intentionallyClosed) {
        reconnectTimer = setTimeout(connect, 3000)
      }
    }
    ws.onerror = () => ws?.close()
    ws.onmessage = ({ data }: MessageEvent<string>) => {
      try {
        const msg = JSON.parse(data) as RealtimeMessage
        if (msg.channel === channelName) {
          handlers.get(msg.event)?.(msg.data)
        }
      } catch {}
    }
  }

  function on(event: string, handler: (data: unknown) => void) {
    handlers.set(event, handler)
  }

  function disconnect() {
    intentionallyClosed = true
    if (reconnectTimer) clearTimeout(reconnectTimer)
    ws?.close()
  }

  onMounted(connect)
  onUnmounted(disconnect)

  return { connected, on, disconnect }
}
