import { pgTable, text, integer, boolean, timestamp, doublePrecision, jsonb, pgEnum, index, uniqueIndex } from 'drizzle-orm/pg-core'

import { relations } from 'drizzle-orm'
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm'

export const userRoleEnum = pgEnum('user_role', ['admin', 'editor', 'viewer'])
export const pageStatusEnum = pgEnum('page_status', ['draft', 'published', 'archived'])
// User table — generated by Vasp auth system
export const users = pgTable('users', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  username: text('username').notNull().unique(),
  email: text('email').unique(),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  githubId: text('github_id').unique(),
  role: userRoleEnum('role').notNull().default('editor'),
  displayName: text('displayName'),
  bio: text('bio'),
  avatar: text('avatar'),
  isActive: boolean('isActive').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})
export type User = InferSelectModel<typeof users>
export type NewUser = InferInsertModel<typeof users>

// Space table — generated from entity block
export const spaces = pgTable('spaces', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  name: text('name').notNull(),
  key: text('key').notNull().unique(),
  description: text('description'),
  iconUrl: text('iconUrl'),
  isPublic: boolean('isPublic').notNull().default(false),
  ownerId: integer('ownerId').notNull().references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  index('spaces_key_idx').on(t.key),
  uniqueIndex('spaces_name_unique').on(t.name),
])
export type Space = InferSelectModel<typeof spaces>
export type NewSpace = InferInsertModel<typeof spaces>

// Page table — generated from entity block
export const pages = pgTable('pages', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  title: text('title').notNull(),
  body: text('body'),
  status: pageStatusEnum('status').notNull(),
  version: integer('version').notNull().default(1),
  excerpt: text('excerpt'),
  slug: text('slug'),
  isFeatured: boolean('isFeatured').notNull().default(false),
  viewCount: integer('viewCount').notNull().default(0),
  spaceId: integer('spaceId').notNull().references(() => spaces.id, { onDelete: 'cascade' }),
  authorId: integer('authorId').notNull().references(() => users.id, { onDelete: 'restrict' }),
  parentId: integer('parentId').references(() => pages.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  index('pages_status_idx').on(t.status),
  index('pages_spaceId_idx').on(t.spaceId),
])
export type Page = InferSelectModel<typeof pages>
export type NewPage = InferInsertModel<typeof pages>

// PageVersion table — generated from entity block
export const pageVersions = pgTable('pageVersions', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  version: integer('version').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  changeNote: text('changeNote'),
  pageId: integer('pageId').notNull().references(() => pages.id, { onDelete: 'cascade' }),
  authorId: integer('authorId').notNull().references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  index('pageVersions_pageId_version_idx').on(t.pageId, t.version),
])
export type PageVersion = InferSelectModel<typeof pageVersions>
export type NewPageVersion = InferInsertModel<typeof pageVersions>

// Comment table — generated from entity block
export const comments = pgTable('comments', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  content: text('content').notNull(),
  isEdited: boolean('isEdited').notNull().default(false),
  editedAt: timestamp('editedAt'),
  pageId: integer('pageId').notNull().references(() => pages.id, { onDelete: 'cascade' }),
  authorId: integer('authorId').notNull().references(() => users.id, { onDelete: 'cascade' }),
  parentId: integer('parentId').references(() => comments.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})
export type Comment = InferSelectModel<typeof comments>
export type NewComment = InferInsertModel<typeof comments>

// Label table — generated from entity block
export const labels = pgTable('labels', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  name: text('name').notNull().unique(),
  color: text('color'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})
export type Label = InferSelectModel<typeof labels>
export type NewLabel = InferInsertModel<typeof labels>

// Attachment table — generated from entity block
export const attachments = pgTable('attachments', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  filename: text('filename').notNull(),
  mimeType: text('mimeType').notNull(),
  sizeBytes: integer('sizeBytes').notNull(),
  url: text('url').notNull(),
  pageId: integer('pageId').notNull().references(() => pages.id, { onDelete: 'cascade' }),
  uploadedById: integer('uploadedById').notNull().references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})
export type Attachment = InferSelectModel<typeof attachments>
export type NewAttachment = InferInsertModel<typeof attachments>

// PageWatch table — generated from entity block
export const pageWatches = pgTable('pageWatches', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  userId: integer('userId').notNull().references(() => users.id, { onDelete: 'cascade' }),
  pageId: integer('pageId').notNull().references(() => pages.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  uniqueIndex('pageWatches_userId_pageId_unique').on(t.userId, t.pageId),
])
export type PageWatch = InferSelectModel<typeof pageWatches>
export type NewPageWatch = InferInsertModel<typeof pageWatches>


export const usersRelations = relations(users, ({ one, many }) => ({
  pages: many(pages),
  comments: many(comments),
  spaces: many(spaces),
}))


export const spacesRelations = relations(spaces, ({ one, many }) => ({
  owner: one(users, { fields: [spaces.ownerId], references: [users.id] }),
  pages: many(pages),
}))

export const pagesRelations = relations(pages, ({ one, many }) => ({
  space: one(spaces, { fields: [pages.spaceId], references: [spaces.id] }),
  author: one(users, { fields: [pages.authorId], references: [users.id] }),
  parent: one(pages, { fields: [pages.parentId], references: [pages.id] }),
  children: many(pages),
  comments: many(comments),
  attachments: many(attachments),
  versions: many(pageVersions),
}))

export const pageVersionsRelations = relations(pageVersions, ({ one, many }) => ({
  page: one(pages, { fields: [pageVersions.pageId], references: [pages.id] }),
  author: one(users, { fields: [pageVersions.authorId], references: [users.id] }),
}))

export const commentsRelations = relations(comments, ({ one, many }) => ({
  page: one(pages, { fields: [comments.pageId], references: [pages.id] }),
  author: one(users, { fields: [comments.authorId], references: [users.id] }),
  parent: one(comments, { fields: [comments.parentId], references: [comments.id] }),
  replies: many(comments),
}))

export const labelsRelations = relations(labels, ({ one, many }) => ({
}))

export const attachmentsRelations = relations(attachments, ({ one, many }) => ({
  page: one(pages, { fields: [attachments.pageId], references: [pages.id] }),
  uploadedBy: one(users, { fields: [attachments.uploadedById], references: [users.id] }),
}))

export const pageWatchesRelations = relations(pageWatches, ({ one, many }) => ({
  user: one(users, { fields: [pageWatches.userId], references: [users.id] }),
  page: one(pages, { fields: [pageWatches.pageId], references: [pages.id] }),
}))


