// Auto-generated by Vasp — do not edit directly
// Universal Vasp plugin — both client and server call the Elysia backend over HTTP.
// On the server, incoming request cookies are forwarded automatically for session continuity.
import { $fetch } from 'ofetch'

interface VaspClient {
  query<T = unknown>(name: string, args?: unknown): Promise<T>
  action<T = unknown>(name: string, args?: unknown): Promise<T>
}

function getCsrfToken(): string | undefined {
  if (import.meta.server) return undefined
  const match = document.cookie.match(/(?:^|;\s*)vasp-csrf=([^;]*)/)
  return match?.[1] !== undefined ? decodeURIComponent(match[1]) : undefined
}

export default defineNuxtPlugin((_nuxtApp) => {
  const config = useRuntimeConfig()
  const baseURL = config.public.apiBase as string

  // Forward the SSR request's cookies to the Elysia backend so session/auth cookies are preserved.
  // `useRequestHeaders()` is a Nuxt composable that reads from the current SSR render context;
  // it returns an empty object on the client (where credentials: 'include' handles cookies instead).
  const forwardHeaders = import.meta.server ? useRequestHeaders(['cookie']) : {}

  const vasp: VaspClient = {
    async query<T = unknown>(name: string, args?: unknown): Promise<T> {
      return $fetch<T>(`/queries/${name}`, {
        baseURL,
        method: 'GET',
        query: args as Record<string, unknown>,
        headers: forwardHeaders,
        credentials: 'include',
      })
    },
    async action<T = unknown>(name: string, args?: unknown): Promise<T> {
      const csrfToken = getCsrfToken()
      return $fetch<T>(`/actions/${name}`, {
        baseURL,
        method: 'POST',
        body: args as BodyInit | Record<string, unknown> | null | undefined,
        headers: {
          ...forwardHeaders,
          ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}),
        },
        credentials: 'include',
      })
    },
  }

  return {
    provide: { vasp },
  }
})
