// Auto-generated by Vasp — do not edit directly
// SSR-aware typed CRUD composables — wrap $fetch with backend URL, auth headers, and CSRF handling.
// On the server, request cookies are forwarded to the Elysia backend for session continuity.
import { $fetch } from 'ofetch'
import { safeParse } from 'valibot'
import type {
  Label,
  CreateLabelInput,
  UpdateLabelInput,
  User,
  UpdateUserInput,
  Page,
  CreatePageInput,
  UpdatePageInput,
} from '@shared/types.js'
import {
  CreateLabelSchema,
  UpdateLabelSchema,
  UpdateUserSchema,
  CreatePageSchema,
  UpdatePageSchema,
} from '@shared/validation.ts'

/** Unwrap the server's `{ ok, data }` envelope. Throws on `ok: false`. */
function unwrap<T>(res: unknown): T {
  if (res && typeof res === 'object' && 'ok' in res) {
    const env = res as { ok: boolean; data?: T; error?: { message?: string } }
    if (!env.ok) throw new Error(env.error?.message ?? 'Request failed')
    return env.data as T
  }
  return res as T
}

export function useLabelCrud() {
  const config = useRuntimeConfig()
  const baseURL = config.public.apiBase as string
  const base = `${baseURL}/crud/label`

  // On the server, forward the incoming request's cookies so the backend can authenticate
  const forwardHeaders = import.meta.server ? useRequestHeaders(['cookie']) : {}

  const loading = ref(false)
  const error = ref<string | null>(null)

  function getCsrfToken(): string | undefined {
    if (import.meta.server) return undefined
    const match = document.cookie.match(/(?:^|;\s*)vasp-csrf=([^;]*)/)
    return match?.[1] !== undefined ? decodeURIComponent(match[1]) : undefined
  }

  const fail = (err: unknown) => {
    error.value = err instanceof Error ? err.message : 'Request failed'
  }

  return {
    loading,
    error,
    list: async (params?: {
      page?: number
      limit?: number
      sortBy?: 'name'
      dir?: 'asc' | 'desc'
      search?: string
    }): Promise<{
      items: Label[]
      total: number
      page: number
      limit: number
    }> => {
      loading.value = true
      error.value = null
      try {
        const query: Record<string, string | number | undefined> = {}
        if (params?.limit !== undefined) query.limit = params.limit
        if ((params as { page?: number } | undefined)?.page !== undefined) query.page = (params as { page?: number }).page
        if ((params as { sortBy?: string } | undefined)?.sortBy) query.sortBy = (params as { sortBy?: string }).sortBy
        if ((params as { dir?: string } | undefined)?.dir) query.dir = (params as { dir?: string }).dir
        if ((params as { search?: string } | undefined)?.search) query.search = (params as { search?: string }).search
        return unwrap(await $fetch(base, { query, headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    create: async (data: CreateLabelInput): Promise<Label> => {
      const parsed = safeParse(CreateLabelSchema, data)
      if (!parsed.success) {
        const msg = parsed.issues?.[0]?.message ?? 'Invalid input'
        const err = new Error(msg)
        fail(err)
        throw err
      }

      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return unwrap(await $fetch(base, {
          method: 'POST',
          body: parsed.output,
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    get: async (id: number): Promise<Label> => {
      loading.value = true
      error.value = null
      try {
        return unwrap(await $fetch(`${base}/${id}`, { headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    update: async (id: number, data: UpdateLabelInput): Promise<Label> => {
      const parsed = safeParse(UpdateLabelSchema, data)
      if (!parsed.success) {
        const msg = parsed.issues?.[0]?.message ?? 'Invalid input'
        const err = new Error(msg)
        fail(err)
        throw err
      }

      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return unwrap(await $fetch(`${base}/${id}`, {
          method: 'PUT',
          body: parsed.output,
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    remove: async (id: number): Promise<{ ok: boolean }> => {
      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return await $fetch(`${base}/${id}`, {
          method: 'DELETE',
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        })
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
  }
}

export function useUserCrud() {
  const config = useRuntimeConfig()
  const baseURL = config.public.apiBase as string
  const base = `${baseURL}/crud/user`

  // On the server, forward the incoming request's cookies so the backend can authenticate
  const forwardHeaders = import.meta.server ? useRequestHeaders(['cookie']) : {}

  const loading = ref(false)
  const error = ref<string | null>(null)

  function getCsrfToken(): string | undefined {
    if (import.meta.server) return undefined
    const match = document.cookie.match(/(?:^|;\s*)vasp-csrf=([^;]*)/)
    return match?.[1] !== undefined ? decodeURIComponent(match[1]) : undefined
  }

  const fail = (err: unknown) => {
    error.value = err instanceof Error ? err.message : 'Request failed'
  }

  return {
    loading,
    error,
    list: async (params?: {
      page?: number
      limit?: number
      sortBy?: 'username' | 'email' | 'createdAt'
      dir?: 'asc' | 'desc'
      filter?: Partial<Record<'role' | 'isActive', string>>
      search?: string
    }): Promise<{
      items: User[]
      total: number
      page: number
      limit: number
    }> => {
      loading.value = true
      error.value = null
      try {
        const query: Record<string, string | number | undefined> = {}
        if (params?.limit !== undefined) query.limit = params.limit
        if ((params as { page?: number } | undefined)?.page !== undefined) query.page = (params as { page?: number }).page
        if ((params as { sortBy?: string } | undefined)?.sortBy) query.sortBy = (params as { sortBy?: string }).sortBy
        if ((params as { dir?: string } | undefined)?.dir) query.dir = (params as { dir?: string }).dir
        if ((params as { filter?: Record<string, string | undefined> } | undefined)?.filter) {
          for (const [k, v] of Object.entries((params as { filter: Record<string, string | undefined> }).filter)) {
            if (v !== undefined) query[`filter.${k}`] = v
          }
        }
        if ((params as { search?: string } | undefined)?.search) query.search = (params as { search?: string }).search
        return unwrap(await $fetch(base, { query, headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    get: async (id: number): Promise<User> => {
      loading.value = true
      error.value = null
      try {
        return unwrap(await $fetch(`${base}/${id}`, { headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    update: async (id: number, data: UpdateUserInput): Promise<User> => {
      const parsed = safeParse(UpdateUserSchema, data)
      if (!parsed.success) {
        const msg = parsed.issues?.[0]?.message ?? 'Invalid input'
        const err = new Error(msg)
        fail(err)
        throw err
      }

      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return unwrap(await $fetch(`${base}/${id}`, {
          method: 'PUT',
          body: parsed.output,
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
  }
}

export function usePageCrud() {
  const config = useRuntimeConfig()
  const baseURL = config.public.apiBase as string
  const base = `${baseURL}/crud/page`

  // On the server, forward the incoming request's cookies so the backend can authenticate
  const forwardHeaders = import.meta.server ? useRequestHeaders(['cookie']) : {}

  const loading = ref(false)
  const error = ref<string | null>(null)

  function getCsrfToken(): string | undefined {
    if (import.meta.server) return undefined
    const match = document.cookie.match(/(?:^|;\s*)vasp-csrf=([^;]*)/)
    return match?.[1] !== undefined ? decodeURIComponent(match[1]) : undefined
  }

  const fail = (err: unknown) => {
    error.value = err instanceof Error ? err.message : 'Request failed'
  }

  return {
    loading,
    error,
    list: async (params?: {
      page?: number
      limit?: number
      sortBy?: 'title' | 'createdAt' | 'updatedAt' | 'status'
      dir?: 'asc' | 'desc'
      filter?: Partial<Record<'status', string>>
      search?: string
    }): Promise<{
      items: Page[]
      total: number
      page: number
      limit: number
    }> => {
      loading.value = true
      error.value = null
      try {
        const query: Record<string, string | number | undefined> = {}
        if (params?.limit !== undefined) query.limit = params.limit
        if ((params as { page?: number } | undefined)?.page !== undefined) query.page = (params as { page?: number }).page
        if ((params as { sortBy?: string } | undefined)?.sortBy) query.sortBy = (params as { sortBy?: string }).sortBy
        if ((params as { dir?: string } | undefined)?.dir) query.dir = (params as { dir?: string }).dir
        if ((params as { filter?: Record<string, string | undefined> } | undefined)?.filter) {
          for (const [k, v] of Object.entries((params as { filter: Record<string, string | undefined> }).filter)) {
            if (v !== undefined) query[`filter.${k}`] = v
          }
        }
        if ((params as { search?: string } | undefined)?.search) query.search = (params as { search?: string }).search
        return unwrap(await $fetch(base, { query, headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    create: async (data: CreatePageInput): Promise<Page> => {
      const parsed = safeParse(CreatePageSchema, data)
      if (!parsed.success) {
        const msg = parsed.issues?.[0]?.message ?? 'Invalid input'
        const err = new Error(msg)
        fail(err)
        throw err
      }

      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return unwrap(await $fetch(base, {
          method: 'POST',
          body: parsed.output,
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    get: async (id: number): Promise<Page> => {
      loading.value = true
      error.value = null
      try {
        return unwrap(await $fetch(`${base}/${id}`, { headers: forwardHeaders, credentials: 'include' }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    update: async (id: number, data: UpdatePageInput): Promise<Page> => {
      const parsed = safeParse(UpdatePageSchema, data)
      if (!parsed.success) {
        const msg = parsed.issues?.[0]?.message ?? 'Invalid input'
        const err = new Error(msg)
        fail(err)
        throw err
      }

      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return unwrap(await $fetch(`${base}/${id}`, {
          method: 'PUT',
          body: parsed.output,
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        }))
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
    remove: async (id: number): Promise<{ ok: boolean }> => {
      loading.value = true
      error.value = null
      try {
        const csrfToken = getCsrfToken()
        return await $fetch(`${base}/${id}`, {
          method: 'DELETE',
          headers: { ...forwardHeaders, ...(csrfToken ? { 'x-csrf-token': csrfToken } : {}) },
          credentials: 'include',
        })
      } catch (err) {
        fail(err)
        throw err
      } finally {
        loading.value = false
      }
    },
  }
}

