// Auto-generated by Vasp — do not edit directly
interface VaspClient {
  query<T = unknown>(name: string, args?: unknown): Promise<T>
  action<T = unknown>(name: string, args?: unknown): Promise<T>
}

export const useVasp = (): { $vasp: VaspClient } => {
  const { $vasp } = useNuxtApp()
  return { $vasp: $vasp as VaspClient }
}
